name: Analyze project

on:
  push:
    branches:
      - "*/*"

jobs:
  test:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
          cache: 'gradle'
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.2"
          cache: true
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
